language: php

php:
  - 7.3
  - master

env:
  matrix:
    - dependencies=lowest
    - dependencies=highest

matrix:
  allow_failures:
    - php: master

before_script:
  - if php --ri xdebug >/dev/null; then phpenv config-rm xdebug.ini; fi

install:
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --no-interaction; fi
  - if [ "$dependencies" = "highest" ]; then composer update --no-interaction; fi

script:
  - vendor/bin/phpunit tests

cache:
  directories:
    - $HOME/.composer/cache
