name: CI

on: [push]

jobs:
  test-php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3, 7.4]
        composer: ['', '--prefer-lowest']
    steps:
    - uses: actions/checkout@v1
    - name: Change PHP version
      run: |
        if [ "${{ matrix.php }}" = "7.4" ]; then \
          packages=$(apt-cache search php7.4- | grep ^php | grep -v ^php7.4-fpm | awk '{print $1}' | awk '{print $1}' | tr '\n' ' ');
          sudo apt-get install -y php7.4 $packages; \
        fi
        ls -la /usr/bin/php*
        sudo update-alternatives --set php /usr/bin/php${{ matrix.php }} && php -v
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Composer update
      run: composer update ${{ matrix.composer }} --no-progress
    - name: PhpUnit
      continue-on-error: ${{ matrix.php == 7.4 }}
      run: php -d xdebug.profiler_enable=off ./vendor/bin/phpunit tests
